### ISSUE TITLE
Full Page - Bio quotes and images

### ISSUE THREAD

**Issue by lettiem** [anhnt/paspaley#14]
@anhnt Please insert these quotes above each of the respective bio copy along with their respective black & white photo attached.

Ariel Kleiman
“I really enjoyed this project - having the creative freedom to develop this film, working with great
 people like Paspaley and Clara, not to mention the once in a lifetime opportunity to shoot in such a stunning location.”

Clara Paget
“While the amazing jewellery and the amazing Kimberley region certainly drew me to this project, the opportunity to work with Regan and Ariel to merge the worlds of acting and modelling was very interesting to me.”

Regan Cameron
“This was exactly my sort of project. I’ve always wanted to shoot in The Kimberley, what an amazing location, and Clara is a truly inspiring model - but to have my photography integrated into the world of film is pretty exciting.”

Christine Salter
“This campaign captures the modernity and versatility of our latest collection, while showcasing a location so unique to my family’s 80 year pearling heritage.”

**Comment by anhnt** [comment]
@lettiem 
I've added the text. Please check here http://version5.paspaley.olhub.com/
The bio name font is not correct, please provide me Futura Bold font family
