### ISSUE TITLE
Microsite Header & Footer Nav and Yellow Subscribe Bar sticking

### ISSUE THREAD

**Issue by lettiem** [anhnt/paspaley#16]
@anhnt please develop the following:
- Header and Footer navigation floats and stays on top at all times while you scroll up and down the page (same functionality as what is currently on the Paspaley.com site)
- Yellow subscribe bar will stick underneath the image carousel, but when you scroll down the page the yellow subscribe bar will stick directly underneath the Header nav. This gives the user opportunity to sing-up no matter how far down they are on the microsite
- When you scroll to the top of the page the yellow subscribe bar will sit straight underneath the carousel

Develop this so that there is no white gap issue

**Comment by anhnt** [comment]
@lettiem I've done this. Can you please test it?

http://version5.paspaley.olhub.com
