### ISSUE TITLE
Full page Sept 15

### ISSUE THREAD

**Issue by anhnt** [anhnt/paspaley#2]
Make changes to "Full Page” - http://anh.link:2800/
- This page is now due to go live on the 15th Sept
- Please apply PSD design that was sent to you on Thursday, 3 Sept 2015
- The hero image will be a carousel, so please apply x3 rotating placeholder images
- The client has also advised that there will be 3 x 15 second video clips that needs to go live on this page. As a placeholder could you please insert on top of the carousel the custom YouTube video player that you worked on into this page?
- With the custom YouTube video, could you please:
- swap out the music video with this placeholder video https://www.youtube.com/watch?v=ABM-VA-8Ryc. If you can’t use this video please just choose any Paspaley video from their YouTube channel https://www.youtube.com/channel/UC4fc_YVXFXQZhJB5c-3xBcA
- With the overlay Official Merchandise 'i’ button please change this to "Shop the Maxima Collection - Click Here”
- When the right hand side panel appears after clicking on the ‘i’ button could you please change these to Paspaley products - just pick any of the products on http://www.paspaley.com/eboutique/
- Please drop in the attached copy deck for the microsite and EDMs. Please note this copy deck is still being approved so we are expecting the client to make some copy tweaks before going live.
- With the location images, could you please make the images randomly change every time someone visits the microsite?

FYI - I am still waiting on the creative agency to send PSDs for all the EDMs and all the other microsite pages. The client has now changed the go live dates to the following:

·         Sept 9: Coming Soon Holding Page go-live (collect subscriptions from this date)
·         Sept 14: Image Carousel or 3 x 15 second YouTube video clips, Bios, Location images go live.
·         Sept 21: 30 second Trailer Youtube video released on microsite page
·         Sept 29: Registration now closed pop-up goes live. 25 winners are picked and an EDM is sent to all these 25 winners on 5pm AEST on the 29th October. All those who subscribe receive an EDM of the full pre-release short film on the 1st Oct – this EDM will click through to the “Hidden Pre-release Short Film Page". Everyone else can publicly view this short film on the microsite from October 2.
·         Oct 1: Maxima collection live on microsite
·         Oct 2: Short film released on microsite
·         Oct 7: EDM new collection now live

Youtube: https://youtu.be/ABM-VA-8Ryc

Mail: https://mail.google.com/mail/u/0/#inbox/14f98325d4fdcca3

**Comment by lettiem** [comment]
@anhnt when will you have this completed for testing? Want to send this over to Paspaley sometime this week for their review

**Comment by anhnt** [comment]
@lettiem It is in progress but almost should be done tomorrow

**Comment by lettiem** [comment]
@anhnt I need to send you more assets. I will open up new issues for these.

**Comment by lettiem** [comment]
@anhnt the client wants to see this on Friday for testing. But the Creative Agency has advised they won't have final assets ready in time... They have given us 2 versions (with placeholders) of this Full Page: 1 version with image carousel at the top and another version that replaces the image carousel with the x3 video clips.

Instead of you developing 2 different pages, is it easier for you to build on 1 page the carousel panel at the top and underneath it the 3x video panel? And we can comment out which one they would like to test first?

Due to the short timeframe I'm just trying to find the best way to make things easier and speed things up for you.

What do you think?

**Comment by lettiem** [comment]
@anhnt Client has just confirmed that for 14 Sept they only want to go live with the image carousel, bios and environment location shots (location shots needs to randomly change every time someone visits the site).

On the 21st Sept we will go live with the Youtube video panel of the video clips and trailer. This video panel will replace the image carousel.
