### ISSUE TITLE
eDM doesnt match the PSD

### ISSUE THREAD

**Issue by anhnt** [anhnt/paspaley#4]
The below EDM doesn’t match the PSD. Please fix following:
- I think in the PSD there is a grey background colour behind the body copy.
- The hero image is a little low res, we will need to send you the retouched image, but for the purposes testing and getting client approval could please fix resolution of this placeholder image?
- The font type and font spacing don’t seem to match. When I checked the EDM in Mac Mail there is no line breaks in between the paragraphs, see screenshot attached. But when I checked the EDM on my hotmail account the line spacing of the copy in the yellow bar is out, see attached image.

**Comment by lettiem** [comment]
@anhnt I am unable to test these changes because it keeps saying that I am already registered. Could you please delete our sign-ups so that we can test again? Also please send us instructions on how to delete these entries in Kademi.

**Comment by anhnt** [comment]
@lettiem I will delete the old data shortly. FYI - You can click unsubscribe button to remove the membership from now

**Comment by lettiem** [comment]
@anhnt with the unsubscribe please delete copy "and you will not be able to login." and also in the pop-up window that appears when you click unsubscribe, please delete copy "You will no longer be able to access this site"

**Comment by anhnt** [comment]
@lettiem done!

**Comment by lettiem** [comment]
@anhnt unsubscribe looks good. But when I click on OK in the pop-up window that says "Are you sure you want to unsubscribe?" it takes me to another pop-up prompting me to login. When I click on the "unsubscribe" link in the EDM again it takes me to a page prompting me to login. See screenshots attached - I was testing this on my Mac laptop, this issue doesn't occur on iPhone and iPad mini.
![screen shot 2015-09-06 at 10 38 00 am](https://cloud.githubusercontent.com/assets/9561347/9701854/e65a5604-5483-11e5-870e-b8f5a2ab1361.png)
![screen shot 2015-09-06 at 10 39 59 am](https://cloud.githubusercontent.com/assets/9561347/9701855/e65f62de-5483-11e5-8396-85b0a5a026a9.png)

**Comment by anhnt** [comment]
@lettiem  This is very strange. I have tried few times but couldnt reproduce it. Can you please send me the link to unsubscribe page?

**Comment by lettiem** [comment]
@anhnt have you managed to fix this unsubscribe login issue? It appears to still be happening. This is how I got the login page:
- I clicked on the "To unsubscribe please click here" link in the EDM
- I am taken to the unsubscribe page. I click on my email address to confirm unsubscribe
- A pop-up appears saying "Are you sure you want to unsubscribe". I click OK
- I then go back to the EDM and click on "To unsubscribe please click here" 
- I am then taken to a page that says "Please login to view this page" - can we remove this page altogether?

**Comment by anhnt** [comment]
@lettiem I tried to reproduce this in both chrome and firefox in incognito mode as well as normal mode but it seems to work properly without any issue. Can you try in incognito mode to ensure browser cache is fresh?

**Comment by lettiem** [comment]
@anhnt I am using Firefox. How do I incognito mode in Firefox?

**Comment by lettiem** [comment]
@anhnt I figured out how to do incognito mode in Firefox - they call it "New Private Window". When I unsubscribed in incognito mode I got the "Authentication Required" pop-up. And when I click on the unsubscribe link in the EDM again I was taken to the login page, see screenshots below
![screen shot 2015-09-09 at 11 27 14 am](https://cloud.githubusercontent.com/assets/9561347/9751291/2c21c352-56e6-11e5-9762-8b536cc14495.png)
![screen shot 2015-09-09 at 11 29 09 am](https://cloud.githubusercontent.com/assets/9561347/9751292/2c275e52-56e6-11e5-85c6-2d5bf0411556.png)

**Comment by anhnt** [comment]
@lettiem I got the authentication popup but not the login screen. Let me find what problem is

**Comment by lettiem** [comment]
@anhnt is this now fixed?
