### ISSUE TITLE
Client feedback

### ISSUE THREAD

**Issue by anhnt** [anhnt/paspaley#5]
·         Please amend t’s and c’s to the attached
·         Please ensure the “country” drop down is not mandatory to fill out
·         Please ensure “Maxima” and “Maxima by Paspaley” are always in italics
·         Please ensure mother-of-pearl is always spelt lower case and hyphenated
·         The pop up subscribe box has a pre-highlighted box for the premiere – this should be clear, and the user clicks it manually as the CTA is to “check the box”
·         Can the icons be reordered to Facebook, Instagram and YouTube?
·         The font on the image is really blurry
·         The image is not retouched
·         None of the links are working – all should link to the correct areas on Paspaley.com – a lot a saying “page not found”?
·         “Collection coming soon” should just read: “Jewellery Collections” and link to the collections pages
·         The EDM images are distorted – see attached from inbox and mobile
·         EDM copy had not been updated – please see attached.
·         All EDMs should include social icons – maybe “SHARE” or “Follow” with all 3 icons along the footer?
·         The EDM also has no logo on it? Or click to go back to the microsite?

**Comment by anhnt** [comment]
Done:
· Please ensure the “country” drop down is not mandatory to fill out
· The pop up subscribe box has a pre-highlighted box for the premiere – this should be clear, and the user clicks it manually as the CTA is to “check the box”
· Can the icons be reordered to Facebook, Instagram and YouTube?
~~~· The image is not retouched~~~

**Comment by nathandawes** [comment]
Did you receive the files to Download that has some design changes to holding page and changed email template?

**Comment by nathandawes** [comment]
They really want it pixel perfect! 👍😄

**Comment by anhnt** [comment]
yes I got the psds. Will check them shortly

**Comment by nathandawes** [comment]
Something else to flag re links: all should be www.paspaley.com...... Not just Paspaley.com……

As not having the www. Blocks us internally from viewing.

**Comment by anhnt** [comment]
I've fixed all links with www. please check it
