### ISSUE TITLE
Segment Groups

### ISSUE THREAD

**Issue by lettiem** [anhnt/paspaley#6]
@anhnt Just to confirm the segments, this is what I need you to create in Kademi for the registrations

Coming Soon Page - live on 9th SEpt
- Coming soon group
- Premiere Launch Competition group

Full Page - live 14th Sept
- 2015 Registrations - when people submit the registration form they will need to be added to this group
- Please rename group "2014 Registrations" to "Paspaley 2014 Database". We will be sending an EDM to this group. When people from this group click-thru to the microsite from the EDM and they register they will need to fall into another group called "2014 Registrations"
- Create a new group called "Paspaley Existing Client Database" - I need to send you another CSV file to upload to this group
- Create a new group called "Existing Clients". We will be sending an EDM to this group. When people from this group click-thru to the microsite from the EDM and they register they need to fall into group "Existing Clients"
- Premiere-Launch-Competition - will include people who registered from "Coming Soon", "2015 Registrations," "2014 Registrations" and "Existing Clients"

We need to keep these groups separate for tracking and auto-trigger EDM purposes.

Let me know if you have any questions.

**Comment by lettiem** [comment]
@anhnt I'm just reviewing the copy deck. Could you please rename the following groups so that it is consistent with the client's copy deck for reporting purposes:

Rename "Existing Clients" to "All Existing Paspaley Database"
Rename "2014 Registrations" to "2014 Everything Precious Database"

I know its a little confusing but need to keep it consistent for report tracking.

**Comment by anhnt** [comment]
@lettiem I've updated the groups. Please check
